yardLength = float(input())
yardWidth = float(input())
houseLength = float(input())
houseWidth = float(input())
squaremeter = float(yardLength * yardWidth - houseLength * houseWidth)
wage = float(squaremeter * 2)
print(wage)